/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form_Login;

import Hiberneat.User.User;
import java.awt.Toolkit;
import java.io.UnsupportedEncodingException;
import java.util.Date;
import java.util.List;
import java.util.Properties;
import java.util.Random;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.persistence.Query;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.bytebuddy.utility.RandomString;

/**
 *
 * @author admin
 */
public class Form_ForgetPassword extends javax.swing.JFrame {

    /**
     * Creates new form Form_ForgetPassword
     */
    String randomCode;
    private Vector<Object> ArrayEmail;
    private String CheckCode;
    User user;

    public Form_ForgetPassword() {
        initComponents();
        setTitle("Quên Mật Khẩu");
        ImageIcon img = new ImageIcon("src\\main\\java\\img\\icons8_lock_20px_2.png");
        setIconImage(img.getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JP3 = new javax.swing.JPanel();
        btndongy = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cknpass = new javax.swing.JCheckBox();
        txtnewpasss1 = new javax.swing.JPasswordField();
        txtNewpass = new javax.swing.JPasswordField();
        JP2 = new javax.swing.JPanel();
        jTextPane3 = new javax.swing.JTextPane();
        jTextPane2 = new javax.swing.JTextPane();
        btncode = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtverycode = new javax.swing.JTextField();
        JP1 = new javax.swing.JPanel();
        jTextPane1 = new javax.swing.JTextPane();
        btntieptuc = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setIconImages(null);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("src\\main\\java\\img\\icons8_forgot_password_50px.png"));
        jLabel1.setText("Quên Mật Khẩu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 424, 100);

        JP3.setBackground(new java.awt.Color(255, 255, 255));
        JP3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        JP3.setLayout(null);

        btndongy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btndongy.setIcon(new javax.swing.ImageIcon("src\\main\\java\\img\\icons8_checkmark_20px_1.png"));
        btndongy.setText("Đồng Ý");
        btndongy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndongyActionPerformed(evt);
            }
        });
        JP3.add(btndongy);
        btndongy.setBounds(20, 250, 360, 38);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("New Password");
        JP3.add(jLabel2);
        jLabel2.setBounds(20, 10, 210, 60);

        cknpass.setText("Hiện Mật Khẩu");
        cknpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cknpassMouseClicked(evt);
            }
        });
        JP3.add(cknpass);
        cknpass.setBounds(20, 210, 360, 20);

        txtnewpasss1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnewpasss1FocusGained(evt);
            }
        });
        JP3.add(txtnewpasss1);
        txtnewpasss1.setBounds(20, 140, 360, 40);

        txtNewpass.setToolTipText("");
        txtNewpass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNewpassFocusGained(evt);
            }
        });
        JP3.add(txtNewpass);
        txtNewpass.setBounds(20, 80, 360, 40);

        getContentPane().add(JP3);
        JP3.setBounds(10, 120, 400, 330);

        JP2.setBackground(new java.awt.Color(255, 255, 255));
        JP2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        JP2.setLayout(null);

        jTextPane3.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jTextPane3.setText("Please Enter the  Code you were sent by Email");
        jTextPane3.setToolTipText("");
        jTextPane3.setEnabled(false);
        JP2.add(jTextPane3);
        jTextPane3.setBounds(20, 50, 360, 60);

        jTextPane2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jTextPane2.setText("Enter Your Code ");
        jTextPane2.setEnabled(false);
        JP2.add(jTextPane2);
        jTextPane2.setBounds(20, 10, 360, 100);

        btncode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btncode.setText("Verify Code");
        btncode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncodeActionPerformed(evt);
            }
        });
        JP2.add(btncode);
        btncode.setBounds(20, 237, 360, 38);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon("src\\main\\java\\img\\icons8_send_email_20px.png"));
        jPanel5.add(jLabel4);
        jLabel4.setBounds(20, 17, 30, 20);

        txtverycode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtverycode.setText("Code");
        txtverycode.setBorder(null);
        txtverycode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtverycodeMouseClicked(evt);
            }
        });
        jPanel5.add(txtverycode);
        txtverycode.setBounds(60, 1, 295, 45);

        JP2.add(jPanel5);
        jPanel5.setBounds(20, 150, 360, 50);

        getContentPane().add(JP2);
        JP2.setBounds(10, 120, 400, 330);

        JP1.setBackground(new java.awt.Color(255, 255, 255));
        JP1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        JP1.setLayout(null);

        jTextPane1.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jTextPane1.setText("Vui lòng cung cấp những thông tin bên dưới để đặt lại mật khẩu");
        jTextPane1.setEnabled(false);
        JP1.add(jTextPane1);
        jTextPane1.setBounds(20, 10, 360, 99);

        btntieptuc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btntieptuc.setIcon(new javax.swing.ImageIcon("src\\main\\java\\img\\icons8_send_comment_20px_3.png"));
        btntieptuc.setText("Gửi");
        btntieptuc.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        btntieptuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntieptucActionPerformed(evt);
            }
        });
        JP1.add(btntieptuc);
        btntieptuc.setBounds(20, 237, 360, 38);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon("src\\main\\java\\img\\icons8_send_email_20px.png"));
        jPanel3.add(jLabel3);
        jLabel3.setBounds(20, 17, 30, 20);

        txtemail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtemail.setText("Email");
        txtemail.setBorder(null);
        txtemail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtemailMouseClicked(evt);
            }
        });
        jPanel3.add(txtemail);
        txtemail.setBounds(60, 1, 295, 45);

        JP1.add(jPanel3);
        jPanel3.setBounds(20, 150, 360, 50);

        getContentPane().add(JP1);
        JP1.setBounds(10, 120, 400, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtemailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtemailMouseClicked
        txtemail.setText("");
    }//GEN-LAST:event_txtemailMouseClicked

    private void btntieptucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntieptucActionPerformed
        if (txtemail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui Lòng Nhập Email Vào không Để Trống");
        } else {
            if (CheckEMailID()) {
                if (checkMail()) {
                    JP2.show();
                    JP1.hide();
                    JP3.hide();
                }

            } else {
                JOptionPane.showMessageDialog(this, "Email Này không Tồn Tại Vui Lòng Nhập Đúng Email");
            }
        }


    }//GEN-LAST:event_btntieptucActionPerformed
//    private boolean CheckListEmail() {
//        Const.ListUser = null;
//        Query q = Const.session.createQuery("FROM User");
//        Const.ListUser = q.getResultList();
//        ArrayEmail = new Vector<>();
//        for (int i = 0; i < Const.ListUser.size(); i++) {
//
//            ArrayEmail.add(Const.ListUser.get(i).getEmail());
//        }
//        for (int i = 0; i < ArrayEmail.size(); i++) {
//            if (txtemail.getText().equals(ArrayEmail.get(i))) {
//                CheckEMailID();
//                return true;
//
//            }
//        }
//        return false;
//    }

    private boolean CheckEMailID() {
        Const.ListUser = null;
        Query q = Const.session.createQuery("FROM User");
        Const.ListUser = q.getResultList();
        String Email = txtemail.getText();
        for (int i = 0; i < Const.ListUser.size(); i++) {

            if (Email.equals(Const.ListUser.get(i).getEmail())) {
                user = new User();
                user.setId(Const.ListUser.get(i).getId());
                return true;
            }

        }
        return false;
    }

    private boolean ChecktypeMail() {
        Pattern Check = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
        String Email = txtemail.getText();
        if (Check.matcher(Email).find()) {

            return true;

        }
        return false;
    }

    private boolean checkMail() {
        RandomString random = new RandomString(6);
        randomCode = random.nextString();
        final String fromEmail = "thuykieunguyen310@gmail.com"; //Email Gửi
//      final String Password = "etqhxcumxrodcatq"; //MK Ung Dung(etqhxcumxrodcatq)
        final String toEmail = txtemail.getText();
        final String subject = "Reseting code";
        final String message = "Your reset Code is " + randomCode;
    
        MimeMessage msg = new MimeMessage(Const.SessionEMail);
        try {
            msg.addHeader("Content-type", "text/HTML; charset=UTF-8");
            msg.addHeader("format", "flowed");
            msg.addHeader("Content-Transfer-Encoding", "8bit");
            try {
                msg.setFrom(new InternetAddress(fromEmail, "NoReply-JD"));
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(Form_ForgetPassword.class.getName()).log(Level.SEVERE, null, ex);
            }
            msg.setReplyTo(InternetAddress.parse(fromEmail, false));
            msg.setSubject(subject, "UTF-8");
            msg.setText(message, "UTF-8");
            msg.setSentDate(new Date());
            msg.setRecipients(Message.RecipientType.TO, InternetAddress.parse(toEmail, false));
            Transport.send(msg);
            CheckCode = randomCode;
            return true;

        } catch (MessagingException ex) {
            Logger.getLogger(Form_ForgetPassword.class.getName()).log(Level.SEVERE, null, ex);
            return false;
        }
    }
    private void btncodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncodeActionPerformed
        if (txtverycode.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng Nhập Vào Mã Code Được Gửi đến Email Của Bạn");
        } else {
            if (checkCode()) {

                JP1.hide();
                JP2.hide();
                JP3.show();
            } else {
                JOptionPane.showMessageDialog(this, "Code Bạn Nhập Sai Vui lòng Nhập Lại");
            }
        }

    }//GEN-LAST:event_btncodeActionPerformed

    private void txtverycodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtverycodeMouseClicked
        txtverycode.setText("");
    }//GEN-LAST:event_txtverycodeMouseClicked

    private void btndongyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndongyActionPerformed
        if (txtNewpass.getText().isEmpty() && txtnewpasss1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng Nhập Vào Mật khẩu Mới");
        } else {
            User Update = Const.session.get(User.class, user.getId());
            Update.setPassword(txtNewpass.getText());
            if (txtNewpass.getText().equals(txtnewpasss1.getText())) {
                Const.session.getTransaction().begin();
                Const.session.save(Update);
                Const.session.getTransaction().commit();
                JOptionPane.showMessageDialog(this, "Bạn Đã Thay Đổi Mật Khẩu Mới Thành Công");
                user = null;
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Nhập Lại Mật khẩu Không Giống Nhau");
            }
        }

    }//GEN-LAST:event_btndongyActionPerformed

    private void cknpassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cknpassMouseClicked
        if (cknpass.isSelected()) {
            txtNewpass.setEchoChar((char) 0);
            txtnewpasss1.setEchoChar((char) 0);

        } else {

            txtNewpass.setEchoChar('*');
            txtnewpasss1.setEchoChar('*');
        }
    }//GEN-LAST:event_cknpassMouseClicked

    private void txtNewpassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewpassFocusGained
        txtNewpass.setText("");
    }//GEN-LAST:event_txtNewpassFocusGained

    private void txtnewpasss1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnewpasss1FocusGained
        txtnewpasss1.setText("");
    }//GEN-LAST:event_txtnewpasss1FocusGained

    private boolean checkCode() {

        if (txtverycode.getText().equals(CheckCode)) {
            return true;
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public void Window() {
        JP2.hide();
        JP3.hide();
        JP1.show();
        setSize(440, 520);
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        setLocationRelativeTo(null);
        setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JP1;
    private javax.swing.JPanel JP2;
    private javax.swing.JPanel JP3;
    private javax.swing.JButton btncode;
    private javax.swing.JButton btndongy;
    private javax.swing.JButton btntieptuc;
    private javax.swing.JCheckBox cknpass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JPasswordField txtNewpass;
    private javax.swing.JTextField txtemail;
    private javax.swing.JPasswordField txtnewpasss1;
    private javax.swing.JTextField txtverycode;
    // End of variables declaration//GEN-END:variables
}
