/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form_Login;

import Hiberneat.User.User;
import java.sql.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.persistence.Query;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class Form_AddUser extends javax.swing.JFrame {

    /**
     * Creates new form Form_UpdateUser
     *
     */
    public Form_AddUser() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        txtHoveTen = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTendangnhap = new javax.swing.JTextField();
        jcombonam = new javax.swing.JComboBox<>();
        jcomboquyen = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdiachi = new javax.swing.JTextArea();
        rdn1 = new javax.swing.JRadioButton();
        rnd2 = new javax.swing.JRadioButton();
        txtmatkhau1 = new javax.swing.JTextField();
        Jcombogioitinh1 = new javax.swing.JComboBox<>();
        jcombongay = new javax.swing.JComboBox<>();
        jcombothang = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btndongy = new javax.swing.JButton();
        btnhuybo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông Tin"));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setLayout(null);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Họ Và Tên");
        jPanel6.add(jLabel4);

        jPanel5.add(jPanel6);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Email");
        jPanel9.add(jLabel13);

        jPanel5.add(jPanel9);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Tên Đăng Nhập");
        jPanel8.add(jLabel9);

        jPanel5.add(jPanel8);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Mật Khẩu");
        jPanel4.add(jLabel3);

        jPanel5.add(jPanel4);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Ngày Sinh");
        jPanel10.add(jLabel15);

        jPanel5.add(jPanel10);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Giới Tính");
        jPanel12.add(jLabel11);

        jPanel5.add(jPanel12);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Chức Vụ");
        jPanel15.add(jLabel14);

        jPanel5.add(jPanel15);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Địa Chỉ");
        jPanel11.add(jLabel12);

        jPanel5.add(jPanel11);

        jPanel2.add(jPanel5);
        jPanel5.setBounds(10, 30, 230, 320);

        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.Y_AXIS));

        jPanel21.setAlignmentX(15.0F);
        jPanel21.setLayout(null);

        txtHoveTen.setAlignmentY(0.0F);
        jPanel21.add(txtHoveTen);
        txtHoveTen.setBounds(10, 10, 410, 30);

        txtEmail.setAlignmentY(0.0F);
        jPanel21.add(txtEmail);
        txtEmail.setBounds(10, 50, 410, 30);

        txtTendangnhap.setAlignmentY(0.0F);
        jPanel21.add(txtTendangnhap);
        txtTendangnhap.setBounds(10, 90, 410, 30);

        jcombonam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", " " }));
        jcombonam.setAlignmentX(0.0F);
        jcombonam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcombonamActionPerformed(evt);
            }
        });
        jPanel21.add(jcombonam);
        jcombonam.setBounds(260, 170, 100, 30);

        jcomboquyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "GiaoVien", "SinhVien", "User" }));
        jcomboquyen.setAlignmentX(0.0F);
        jcomboquyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboquyenActionPerformed(evt);
            }
        });
        jPanel21.add(jcomboquyen);
        jcomboquyen.setBounds(10, 250, 100, 30);

        txtdiachi.setColumns(20);
        txtdiachi.setRows(5);
        jScrollPane1.setViewportView(txtdiachi);

        jPanel21.add(jScrollPane1);
        jScrollPane1.setBounds(10, 290, 410, 100);

        rdn1.setText("Bình Thường\n\n");
        rdn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdn1MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rdn1MouseReleased(evt);
            }
        });
        rdn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdn1ActionPerformed(evt);
            }
        });
        jPanel21.add(rdn1);
        rdn1.setBounds(10, 390, 120, 30);

        rnd2.setText("Khóa");
        rnd2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rnd2MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rnd2MouseReleased(evt);
            }
        });
        rnd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rnd2ActionPerformed(evt);
            }
        });
        jPanel21.add(rnd2);
        rnd2.setBounds(150, 390, 120, 30);

        txtmatkhau1.setAlignmentY(0.0F);
        txtmatkhau1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmatkhau1ActionPerformed(evt);
            }
        });
        jPanel21.add(txtmatkhau1);
        txtmatkhau1.setBounds(10, 130, 410, 30);

        Jcombogioitinh1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        Jcombogioitinh1.setAlignmentX(0.0F);
        Jcombogioitinh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jcombogioitinh1ActionPerformed(evt);
            }
        });
        jPanel21.add(Jcombogioitinh1);
        Jcombogioitinh1.setBounds(10, 210, 100, 30);

        jcombongay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " ", " ", " " }));
        jcombongay.setAlignmentX(0.0F);
        jcombongay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcombongayActionPerformed(evt);
            }
        });
        jPanel21.add(jcombongay);
        jcombongay.setBounds(10, 170, 100, 30);

        jcombothang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jcombothang.setAlignmentX(0.0F);
        jcombothang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcombothangActionPerformed(evt);
            }
        });
        jPanel21.add(jcombothang);
        jcombothang.setBounds(140, 170, 100, 30);

        jPanel13.add(jPanel21);

        jPanel2.add(jPanel13);
        jPanel13.setBounds(240, 20, 430, 430);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Trạng Thái");
        jPanel7.add(jLabel7);

        jPanel2.add(jPanel7);
        jPanel7.setBounds(10, 420, 230, 40);

        btndongy.setIcon(new javax.swing.ImageIcon("src\\main\\java\\img\\icons8_checkmark_20px_1.png"));
        btndongy.setText("Đồng Ý");
        btndongy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndongyActionPerformed(evt);
            }
        });
        jPanel2.add(btndongy);
        btndongy.setBounds(250, 470, 140, 30);

        btnhuybo.setIcon(new javax.swing.ImageIcon("src\\main\\java\\img\\icons8_cross_mark_20px.png"));
        btnhuybo.setText("Hủy Bỏ");
        btnhuybo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhuyboActionPerformed(evt);
            }
        });
        jPanel2.add(btnhuybo);
        btnhuybo.setBounds(540, 470, 120, 30);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Thêm Tài Khoản Người Dùng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(111, 111, 111))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcombonamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcombonamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcombonamActionPerformed

    private void jcomboquyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboquyenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcomboquyenActionPerformed

    private void btnhuyboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhuyboActionPerformed
        this.dispose();

    }//GEN-LAST:event_btnhuyboActionPerformed

    private void rdn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdn1MouseClicked

        rnd2.setSelected(false);

    }//GEN-LAST:event_rdn1MouseClicked

    private void rnd2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rnd2MouseClicked

        rdn1.setSelected(false);
    }//GEN-LAST:event_rnd2MouseClicked

    private void rnd2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rnd2MouseReleased
        rdn1.setSelected(false);
    }//GEN-LAST:event_rnd2MouseReleased

    private void rdn1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdn1MouseReleased
        rnd2.setSelected(false);
    }//GEN-LAST:event_rdn1MouseReleased

    private void btndongyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndongyActionPerformed
        int option = JOptionPane.showConfirmDialog(this, "Bạn Có Muốn Thêm Người Dùng Này Không");
        if (option == 0) {
            if (CheckUserName()) {
                JOptionPane.showMessageDialog(this, "Tài Khoản  Này Đã Tồn Tại Vui Lòng Thử Lại Tài Khoản  Khác");
            } else {
                User user = new User();
                user.setHovaTen(txtHoveTen.getText());
                user.setEmail(txtEmail.getText());
                user.setUserName(txtTendangnhap.getText());
                user.setPassword(txtmatkhau1.getText());
                DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
                String NgaySinh = jcombonam.getSelectedItem() + "-" + jcombothang.getSelectedItem() + "-" + jcombongay.getSelectedItem();

                user.setNgaySinh(Date.valueOf(NgaySinh));
                System.out.println("" + NgaySinh);
                user.setGioitinh((String) jcombonam.getSelectedItem());
                user.setQuyen((String) jcomboquyen.getSelectedItem());
                user.setDiaChi(txtdiachi.getText());
                if (rdn1.isSelected()) {
                    user.setTrangThai("Bình Thường");
                } else {
                    user.setTrangThai("Khóa");
                }

                Const.session.save(user);
                JOptionPane.showMessageDialog(this, "Bạn Thêm Thành Công");
                this.dispose();
            }

        } else if (option == 1) {
            JOptionPane.showMessageDialog(this, "Bạn Thêm Thất Bại");
        } else {

        }
    }//GEN-LAST:event_btndongyActionPerformed

    private void rdn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdn1ActionPerformed

    private void rnd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rnd2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rnd2ActionPerformed

    private void txtmatkhau1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmatkhau1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmatkhau1ActionPerformed

    private void Jcombogioitinh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jcombogioitinh1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jcombogioitinh1ActionPerformed

    private void jcombongayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcombongayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcombongayActionPerformed

    private void jcombothangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcombothangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcombothangActionPerformed
    private boolean CheckUserName() {
        Const.ListUser = null;
        Query q = Const.session.createQuery("FROM User");
        Const.ListUser = q.getResultList();
        Vector<Object> CheckuserName = new Vector<>();;
        for (int i = 0; i < Const.ListUser.size(); i++) {

            CheckuserName.add(Const.ListUser.get(i).getUserName());
        }
        for (int i = 0; i < CheckuserName.size(); i++) {
            if (txtTendangnhap.getText().equals(CheckuserName.get(i))) {
                return true;
            }

        }
        return false;
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Jcombogioitinh1;
    private javax.swing.JButton btndongy;
    private javax.swing.JButton btnhuybo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcombonam;
    private javax.swing.JComboBox<String> jcombongay;
    private javax.swing.JComboBox<String> jcomboquyen;
    private javax.swing.JComboBox<String> jcombothang;
    private javax.swing.JRadioButton rdn1;
    private javax.swing.JRadioButton rnd2;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoveTen;
    private javax.swing.JTextField txtTendangnhap;
    private javax.swing.JTextArea txtdiachi;
    private javax.swing.JTextField txtmatkhau1;
    // End of variables declaration//GEN-END:variables

    public void LoadWindow() {

        setSize(749, 690);
        setVisible(true);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(HIDE_ON_CLOSE);

    }
}
